name: Test2789
favicon: null
layout_spectrum: 0.50242
typography_spectrum: 0.5012
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff2944'
    - '#ffffff'
    - '#a20d1f'
    - '#dcb6b9'
    - '#a8444a'
  brandStrength: 0.5
  lightness: 0.6278832457028329
  saturation: 0.3092035921290517
  rhythmicContrast: 0.9827924184501171
purpose: []
