name: Test2789
favicon: null
layout_spectrum: 0.7919062823057175
typography_spectrum: 0.5012
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cdcdcd'
    - '#979ca2'
    - '#002f00'
    - '#63e101'
    - '#924536'
  brandStrength: 0.5
  lightness: 0.6278832457028329
  saturation: 0.3092035921290517
  rhythmicContrast: 0.9827924184501171
purpose: []
